### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by johancc** [johancc/CovEd#16]
There is nothing stopping a parent from requesting help from every mentor. I feel there is a non-zero chance a parent will multiple mentors at once, which would prevent us from reaching more students that need help. 

We should store the last time a parent/student made a request and set some threshold. If the delta between the last request and the current request is below the threshold, we should make a pop up message saying to try again later (similar to the wrong password toast notification).

**Comment by oupadhyay** [comment]
## Comments
Are there any details on how many tutors the tutees are to choose in the description already? If not, we should probably add that.
## Questions
For these:
`router.get("/value", firebaseMiddleware, (req, res) => {`
`router.post("/value", firebaseMiddleware, (req, res) => {`
would we need to add a rate limit to each and every GET and POST request from the api.js? Also, would the rate limits only apply to tutee or to the tutors as well? When writing the if-else conditional, how would we store the time of their last request? 

Can we just count the number of mentors a tutee has and remove them if the mentors cancel and add them as they confirm? An example would be allowing them to request 1 mentor at a time and remove the count if they cancel and "lock" the student with the mentor until any further changes. Throughout this process, we could be ensuring that each tutee only has one mentor "requested."

**Comment by johancc** [comment]
Yeah that system sounds ok, but we will have to add a way for the mentor to accept a student (show it on their profile or something). We can also just set a time constraint. For instance, only let mentees request a mentor every 24 hours, this will prevent a mentee from not being able to request anyone else if a mentor goes MIA

**Comment by oupadhyay** [comment]
I have created a PDF file that goes over my time searching the internet on Rate Limiting. Would this work? Also, are we looking for the custom implementation or the Redis implementation?

[RateLimiting.pdf](https://github.com/johancc/CovEd/files/4485422/RateLimiting.pdf)
