### ISSUE TITLE
Tags don't show up properly on the edit profile page

### ISSUE THREAD

**Issue by johancc** [johancc/CovEd#18]
<img width="638" alt="Annotation 2020-04-13 192448" src="https://user-images.githubusercontent.com/45345485/79179445-7d6f6f00-7dbc-11ea-865f-774f11a79d60.png">

**Comment by sanjayyepuri** [comment]
Does this happen for both tutors and tutees?

**Comment by sanjayyepuri** [comment]
I got this.
