### ISSUE TITLE
Parent email blurb -- any guardian over 18 or if not, email us and we'll figure out

### ISSUE THREAD

**Issue by DheekshuKumar** [johancc/CovEd#24]
At the top of the registration page, we need to add a blurb with specifically worded text.

**Comment by DheekshuKumar** [comment]
At the top of the registration page, we need to add a blurb with specifically worded text.

**Comment by johancc** [comment]
What should the blurb say?

**Comment by DheekshuKumar** [comment]
Something to the effect of "This service is a completely free volunteer-based service. Those under the age of 13 are required to have a form filled out by a parent or guardian. For all others it is strongly recommended that a parent or guardian fill out this form. If a parent or guardian is unable to fill out the form, please email coveducation@gmail.com. Thanks!"
